# /etc/sysctl.d/99-hardening.conf
; semicolons start comments too

net.ipv4.ip_forward = 0
net.ipv4.conf.all.rp_filter=1
  kernel.kptr_restrict =	2
-net.ipv6.conf.all.disable_ipv6 = 1
net.ipv4.ip_local_port_range = 32768	60999
kernel.core_pattern = |/usr/lib/systemd/systemd-coredump %P # not a comment
this line has no equals sign
net.ipv4.ip_forward = 1
